#!/bin/bash

# Author: William Z Chadwick (echocslsk)
# Date Created: 01/30/2023
# Date Modified: 01/30/2023
# Description:
# Usage: backup2

#!/bin/bash

echo "Hello ${USER^}"
echo "I will now back up your home directory ${HOME}"
currentdir=$(pwd)
echo "You are running this script from ${currentdir},"
echo "but I will save the backup in ~/Backups/bashTarBackUps"
echo ". . ."
tar -cf ~/Backups/bashTarBackUps/"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null
echo ". . ."
echo "backup2 script successfully completed"
exit 0
