#!/bin/bash

# Author: William Z Chadwick
# Date Created: 01/30/2023
# Date Modified: 01/30/2023

# Description:
# Based on Zayid's substitution script

# Usage:
# substitution

time=$(date +%H:%m:%S)
echo "Hello, ${USER^} the time right now is $time"

